# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4')),
                ('last_check', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last check')),
                ('last_status_change', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last status change')),
                ('status_info', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'secondary'), (1, 'positive'), (2, 'primary'), (3, 'warning'), (4, 'negative')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'secondary'), (1, 'positive'), (2, 'primary'), (3, 'warning'), (4, 'negative')], default=0)),
                ('status_change', models.DateTimeField()),
                ('status_info', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Host')),
            ],
        ),
    ]
