# Generated by Django 2.0.2 on 2018-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
