# Generated by Django 2.0.2 on 2018-08-07 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20180221_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='counter_last_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last status change'),
        ),
        migrations.AddField(
            model_name='port',
            name='counter_status',
            field=models.IntegerField(choices=[(0, 'secondary'), (1, 'positive'), (2, 'primary'), (3, 'warning'), (4, 'negative')], default=0),
        ),
        migrations.AddField(
            model_name='port',
            name='error_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='port',
            name='is_monitored',
            field=models.BooleanField(default=False),
        ),
    ]
