# Generated by Django 2.1 on 2018-08-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180807_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Log',
            new_name='HostLog',
        ),
    ]
