# Generated by Django 2.1 on 2018-08-09 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20180809_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='portlog',
            name='counter_last_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last status change'),
        ),
        migrations.AddField(
            model_name='portlog',
            name='counter_status',
            field=models.IntegerField(choices=[(0, 'secondary'), (1, 'positive'), (2, 'primary'), (3, 'warning'), (4, 'negative')], default=0),
        ),
        migrations.AddField(
            model_name='portlog',
            name='error_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portlog',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Port'),
        ),
    ]
